valkey-io/libvalkey

.github/workflows/build.yml
src/valkeycluster.c
tests/CMakeLists.txt
tests/client_test.c

* Feature gate all of the cluster tests behind a libevent requirement
* Minor tweak to client_test.c
* Signed correctness fix wrt isdigit for cygwin.

Fix Windows builds and CI

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/db-compatibility.yml
.github/workflows/test.yml
tests/CMakeLists.txt

Fixes most remaining issues in CI (hopefully) to get most jobs green.
- Enable building non-cluster test on FreeBSD in CI
- Don't run tests on Windows in CI workflow "CI"
- CMake correction for libevent header.
- Update compilers in CI build matrix
Use latest available gcc/clang in workflow "CI"
- Fix 32bit build in CI workflow "C/C++ CI"    
Known issue left:
`ci.yml`: Run static checkers - clang-format needed to make it happy.
`build.yml`: Intermittent timing issue in test on `macOS`.
Then additional fixes are required, like updating Actions to remove Github warnings,
and merging of CI jobs, some are redundant..
Other finding: `PLATFORM_FLAGS` is not set on built binaries i.e. tests.

Fix issues in CI

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/coverity.yml
.github/workflows/db-compatibility.yml
.github/workflows/release-drafter.yml
.github/workflows/spellcheck.yml
.github/workflows/test.yml

Pin the Github Actions we use in CI to a release hash according to secure software development best practices,
recommended by the Open Source Security Foundation (OpenSSF).
When developing a CI workflow, it's common to version-pin dependencies (i.e. actions/checkout@v4).
However, version tags are mutable, so a malicious attacker could overwrite a version tag to point to a malicious or vulnerable commit instead. Pinning workflow dependencies by hash ensures the dependency is immutable and its behavior is guaranteed.
See details:
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

Pin Github Action versions in CI 

---

Makefile

* We can specify SHELL = /bin/sh to avoid having to do `$(shell sh -c '<cmd>')` and instead just doing `$(shell <cmd)`.
* Use makefile built-in `word` to parse library version info.
* Minor cleanup of OS specific conditional blocks.
* Remove dead `CXX` assignment (it was required for the qt example).
* re-enable `-pedantic` for FreeBSD

Minor Makefile cleanup

---

include/valkey/sds.h
include/valkey/sockcompat.h
include/valkey/valkey.h

Previously, `long long` was used unconditionally to define `ssize_t` on Windows. This meant it was always a 64-bit value. However, typically the size type is a 32-bit value on 32-bit machines and 64-bit value on 64-bit machines.
This didn't cause any issues until it was used on 32-bit Windows build of `libvalkey-py`. CPython defines the `ssize_t` type as well as `libvalkey`, but it defines the size to be 32 bit on 32 bit machines which caused a compilation error.
This commit changes the typedef to be `SSIZE_T` on Windows. Hence, it will be aligned with everything else.

windows: fix size of `ssize_t`

---

CMakeLists.txt
Makefile
include/valkey/valkey.h
include/valkey/valkey_rdma.h
src/conn.c
src/net.c
src/rdma.c
src/ssl.c
src/valkey.c
src/valkey_private.h
tests/CMakeLists.txt
tests/client_test.c
tests/test.sh
valkey_rdma-config.cmake.in
valkey_rdma.pc.in

Hi,
[Valkey Over RDMA](https://github.com/valkey-io/valkey/pull/477) has been supported as experimental feature since Valkey 8.0. Support RDMA transport for the client side.
There are commits in this PR:
* Fully abstract IO framework
* Fix timing issue on reconnect
* Introduce RDMA transport (experimental)
* cmake related support
These commits are already in order, they have separate function with detailed commit message, so no need to squash them into one.

Introduce RDMA transport (experimental)

---

.github/workflows/ci.yml
Makefile

Fix issue after the RDMA feature delivery; filter out ssl source files again.
Issue found in [CI](https://github.com/valkey-io/libvalkey/actions/runs/10194328609/job/28200692136#step:4:22).
Filter out valkeycluster_ssl.h and only install it when built with USE_SSL.
Additionally update CI to use SSL when verifying the installation.

Correcting source- and headerfile filtering in Makefile

---

.github/workflows/build.yml
.github/workflows/ci.yml
tests/clusterclient.c
tests/clusterclient_async.c
tests/test_utils.h

- Disable code format checker in CI
We can enable it back when we have formatted the code base  via #53.
- Use an Ubuntu version that provides requested compiler in CI.
- Merge CI jobs for `windows`
Includes build corrections for tests on Windows regarding missing timeval.
- Merge CI jobs for `macos`
By only installing missing dependencies we get rid of notifications/warnings in Githubs build summary, like:
`cmake 3.30.1 is already installed and up-to-date...`
`openssl@3 3.3.1 is already installed and up-to-date...`
Together with #59 the CI should start to be green, which makes it easier to deliver changes.
The macOS with SSL tests are still a bit flaky (also seen in hiredis).

CI corrections

---

README.md
docs/standalone.md

Just the non-cluster parts of the code so far.

Initial readme.

---

tests/client_test.c

* Reduce sleep time from 3s to 1s. No need to sleep so long.
* Relax tolerances so we can be pretty sure the server has awakened when we make the next attempt.

Attempt to fix timing test CI failure.

---

.github/workflows/build.yml
CMakeLists.txt
Makefile
tests/CMakeLists.txt
tests/client_test.c
tests/clusterclient.c
tests/clusterclient_async.c
tests/clusterclient_reconnect_async.c
tests/ct_async_glib.c
tests/ct_connection.c
tests/ct_out_of_memory_handling.c
tests/ct_pipeline.c
tests/ct_specific_nodes.c
tests/ut_parse_cmd.c

Enable the same warnings in CMake as used in the Makefile (including `-Werror`).
Enable `-pedantic` in Makefile, as in CMake, to `issue all the warnings demanded by strict ISO C `.
Also fixes:
- Correcting -Wwrite-strings warnings in cluster tests (warns about the deprecated conversion from string constants to `char*`).
- Use the correct libevent2 type `evutil_socket_t` instead of `int` when implementing the libevent2 callback function in our tests. On Windows evutil_socket_t is an intptr_t (long long int) which gives a warning (and error with gcc-14).
(Required by #62)

Converge the warning-flags in Makefile and CMake builds    

---

include/valkey/valkeycluster.h
src/valkeycluster.c

- valkeyClustervCommandToNode()
- valkeyClustervAppendCommandToNode()
From https://github.com/Nordix/hiredis-cluster/pull/231

Add new APIs for variadic cluster commands

---

src/valkeycluster.c

When `valkeyAsyncFormattedCommand()` fail to push a given callback to its internal queue we need to free the `cluster_async_data` used in the cluster part (as privdata).
Additionally; keep the error message from `valkeyAsyncFormattedCommand()`.
This is the corresponding fix to https://github.com/Nordix/hiredis-cluster/pull/234 .

Fix possible leak when failing to send a async cluster command

---

include/valkey/valkeycluster.h
src/valkeycluster.c
tests/CMakeLists.txt
tests/clusterclient_async.c
tests/scripts/client-disconnect-test.sh
tests/scripts/client-disconnect-without-slotmap-update-test.sh

- No slot map updates during a cluster client disconnect.
- Don't follow redirects when a cluster client disconnects.
- Don't accept new commands when a cluster client disconnects.
This is a corresponding change to https://github.com/Nordix/hiredis-cluster/pull/225 .

Don't initiate new connections during a cluster client disconnect (async API)

---

examples/Makefile
examples/async-qt.cpp

If Qt6 is installed the example can be built using:
```
cd examples
QT_MOC=$(qmake -query QT_HOST_LIBEXECS)/moc \
QT_INCLUDE_DIR=$(qmake -query QT_INSTALL_HEADERS) \
QT_LIBRARY_DIR=$(qmake -query QT_INSTALL_LIBS) \
make example-async-qt
./example-async-qt
```

Fix build issues with Qt adapter example

---

.git-blame-ignore-revs
README.md

The first commit adds `.git-blame-ignore-revs` that lists the formatting commit so it would be omitted in `git blame`.
The second commit mentions `clang-format` version in README.

Small changes after formatting

---

.github/release-drafter-config.yml
.github/workflows/release-drafter.yml

Enable the release drafter since it was used in hiredis,
and other clients under https://github.com/valkey-io seems keep using it.

Enable release-drafter in CI

---

include/valkey/valkeycluster.h
src/valkeycluster.c

Rename API functions to get a standalone context from a cluster node, which are needed to support PUB/SUB.
```
ctx_get_by_node  -> valkeyClusterGetValkeyContext
actx_get_by_node -> valkeyClusterGetValkeyAsyncContext
```
- Remove internal `parse_cluster_*` functions from the cluster API. Should not be needed by users.
- Remove deprecated functions in the cluster API.

Rename and remove deprecated functions in the cluster API

---

.github/workflows/ci.yml
tests/client_test.c

Update the CI workflow `ubuntu`:
- Build using the now available GCC 14.
- Build for Release only to use less CPU time.
- Enable sanitizers.
The PR includes:
- Fix `global-buffer-overflow` in client_test
..where the string length of "*1\r\n,3.14159265358979323846\r\n" is 29.

Add sanitizers to CI and fix a found test issue

---

src/cluster.c

Add internal convenience functions to clear errors, and cleanup the internal `SetError` functions.
The error string for `VALKEY_ERR_IO` is set by the standalone API, so removing the handling for it in the cluster part.

Cleanup of internal cluster error functions

---

.github/workflows/build.yml
.github/workflows/ci.yml

- Refactor and move the CI step to build using make.
Run the tests under valgrind on Ubuntu only, which should be enough.
- Add a CMake build with type=Debug to make sure building without `-DNDEBUG` is fine.

CI updates

---

.github/typos.toml
.github/workflows/spellcheck.yml
docs/cluster.md
src/cluster.c
src/read.c
src/sds.c
tests/client_test.c
tests/scripts/command-from-callback-test.sh
tests/scripts/redirect-with-hostname-test.sh
tests/scripts/redirect-with-ipv6-test.sh
tests/scripts/timeout-handling-test.sh

Start using `typos` which also is used in the valkey project.
Includes corrections for found spelling errors.
Closes #17.

Add a source code spellchecker to CI 

---

examples/Makefile
include/valkey/adapters/ae.h
include/valkey/adapters/glib.h
include/valkey/adapters/ivykis.h
include/valkey/adapters/libev.h
include/valkey/adapters/libevent.h
include/valkey/adapters/libhv.h
include/valkey/adapters/libsdevent.h
include/valkey/adapters/libuv.h
include/valkey/adapters/macosx.h
include/valkey/adapters/poll.h
include/valkey/cluster.h
src/cluster.c
tests/clusterclient_async.c
tests/clusterclient_reconnect_async.c
tests/ct_async_glib.c

Attach a cluster context to an event library when an attach function has been registered.
Check the `attach_fn` instead of `data` since the attach data might not be required for some event engines, an can be NULL.
- Add missing cluster event adapters (ivykis, libhv, libsdevent, MacOS, poll)
- Update async cluster testcases
- Updates to makes the async tests and examples build and succeed.

Event adapter corrections

---

src/cluster.c
tests/ct_out_of_memory_handling.c

- Merge `handleClusterSlotsReply` and `handleClusterNodesReply` into `clusterUpdateRouteHandleReply`.
- Validate the reply in  `parse_cluster_slots` and `parse_cluster_nodes`
- Remove redundant argument `flags` in `parse_cluster_slots` and `parse_cluster_nodes`
- Use error strings from the standalone context in both the send function (`clusterUpdateRouteSendCommand`) and the response function (`handleClusterSlotsReply`); making sure that specific error strings are used (like OOM).
- Update OOM test which now get correct error string.

Refactor slotmap update functions

---

CMakeLists.txt
examples/async-libsdevent.c
examples/async-libuv.c
examples/blocking.c
src/cluster.c
tests/client_test.c
tests/ct_async_libuv.c
tests/ct_commands.c
tests/ct_out_of_memory_handling.c
tests/ct_specific_nodes.c
tests/ut_parse_cmd.c

Disable the GNU extensions in CMake, which is ON by default for some reason.
This enables `-std=c99` instead of `-std=gnu99`, same as in the Makefile.
Enable GNU extensions where required in examples and some tests.

Use `-std=c99` when building with CMake

---

.github/workflows/build.yml
.github/workflows/ci.yml

Valkey is now included in Ubuntu:
https://ubuntu.com/blog/valkey-ubuntu

Install the Valkey package when available in CI

---

docs/migration-guide.md
include/valkey/cluster.h
src/cluster.c

The API valkeyClusterSetOptionAddNode**s** can be used instead.
It takes a single address, or multiple comma separated addresses.

Remove API `valkeyClusterSetOptionAddNode`

---

src/cluster.c
tests/ct_out_of_memory_handling.c

It simplifies the code a bit when these are allocated at context initiation.

Create cluster nodes dict and request list when initiating valkeyClusterContext

---

src/cluster.c
tests/ct_out_of_memory_handling.c
tests/ut_slotmap_update.c

This is a 2 step/2 commit refactor PR.
* Refactor the internal function `parse_cluster_nodes`.
Parse the `CLUSTER NODES` reply by a simpler string search using `strchr` and string modification instead of using `sdssplitlen`, which allocates memory for each element.
Parse each line once using a new function `parse_cluster_nodes_line`, which returns a `valkeyClusterNode`.
Replicas are only parsed when configured, like legacy.
* Refactor the replica handling in CLUSTER NODES parsing.
Store parsed replicas in a separate dict during parsing, and move them to their primary when all lines are parsed.
This dict owns the memory for replicas until moved to the related primary node.
Previously the dict contained references to both replicas and primaries and a bit harder to handle.
The function …

 Refactor the internal function `parse_cluster_nodes`

---

include/valkey/rdma.h
src/rdma.c
src/valkey.c
tests/client_test.c
tests/test.sh

Hi @michael-grunder @bjosv 
Each patch has independent functionality, also been tested by CI and local commands, so request no-squash merge for this PR.

RDMA bind local address

---

docs/cluster.md
docs/migration-guide.md
examples/async-glib.c
examples/async-libev.c
examples/async-libevent-tls.c
examples/async-libevent.c
examples/async-libhv.c
examples/async-libsdevent.c
examples/async-libuv.c
examples/cluster-async-tls.c
examples/cluster-async.c
examples/cluster-clientside-caching-async.c
include/valkey/async.h
include/valkey/cluster.h
src/async.c
src/cluster.c
tests/client_test.c
tests/clusterclient_async.c
tests/ct_async.c
tests/ct_async_glib.c
tests/ct_async_libev.c
tests/ct_async_libuv.c
tests/ct_connection.c
tests/ct_out_of_memory_handling.c
tests/ct_pipeline.c
tests/ct_specific_nodes.c

Remove `valkeyAsyncSetConnectCallbackNC` since it was first added in hiredis for backwards-compatibility reasons,
and let `valkeyAsyncSetConnectCallback` use the non-const connect callback prototype.
Includes the removal of the cluster version `valkeyClusterAsyncSetConnectCallbackNC` and updates of tests.

Simplify API by only using non-const connect callbacks

---

src/cluster.c
tests/ut_slotmap_update.c

When parsing a `CLUSTER NODES` response we will now treat an empty IP string as it means the same endpoint as the response came from. This due to that the docs mention that an empty string is returned for the IP field when the node doesn't know its own IP address.
The created `valkeyClusterNode` will get its address from the `valkeyContext` used when sending the command.
Additional changes are that we will use the `noaddr` flag instead of the address length when deciding when a node should be skipped; and added validation of the port.
Example of a response snippet with an empty address:
"752d150249c157c7cb312b6b056517bbbecb42d2 **:6379**@&#65279;16379 myself,master - 1658754833817 1658754833000 3 connected 5461-10922"

Handle empty addresses in `CLUSTER NODES` responses

---

.github/dependabot.yml

Use the grouping feature in `dependabot` to bundle multiple updates into a single PR during the weekly check.

dependabot: bundle multiple dependency updates in one PR

---

tests/ut_slotmap_update.c

Adds `CLUSTER SLOTS` parser tests, which uses a testsuite-local primitive parser of a JSON subset to encode arrays to RESP.

Add cluster slots parsing tests

---

src/cluster.c
tests/CMakeLists.txt
tests/clusterclient_async.c
tests/scripts/connect-during-cluster-startup-test.sh
tests/scripts/connect-during-cluster-startup-using-cluster-nodes-test.sh
tests/scripts/dbsize-to-all-nodes-during-scaledown-test-async.sh
tests/ut_slotmap_update.c

Small fix to reattempt failing slotmap updates.
Additionally:
- Handle empty and NULL addresses in `CLUSTER SLOTS` responses.  
As described in cluster slots docs:
`Clients may treat the empty string in the same way as NULL,
that is the same endpoint it used to send the current command to`
- `clusterclient_async` received a new flag `--async-initial-update` to enable usage of `valkeyClusterAsyncConnect2`, which avoids blocking initial slotmap update.
- Use short timeout when scheduling processing of next command in `clusterclient_async` and allow the event engine to read from sockets before next command, which improves predictability in tests.
Final change similar to https://github.com/Nordix/hiredis-cluster/pull/252.

Retry when an async slotmap update fails 

---

src/tls.c

According to the openss docs `SSL_library_init()` is deprecated as of openssl v1.1.0. We still need to call it when using crypto locks because we define that if openssl is < 1.1.0.
See: https://manpages.debian.org/experimental/libssl-doc/SSL_library_init.3ssl.en.html
See: https://docs.openssl.org/3.3/man3/OPENSSL_init_ssl/

SSL_library_init() is deprecated as of openssl v1.1.0

---

.gitignore

ctags is used widely on a linux platform, add tags into .gitignore.

Add tags into .gitignore

---

src/valkey.c
tests/client_test.c
tests/ct_out_of_memory_handling.c

- Remove inconsistent check of `c->funcs` in `valkeyReconnect`.  
Make sure we always set a `valkeyContextFuncs` before returning from `valkeyConnectWithOptions()`.
We will then always have a `c->funcs` when calling `c->funcs->close`, `c->funcs->connect` and more in multiple places.
**Fixes**: CID443767 "Comparing c->funcs to null implies that c->funcs might be null"
- Fix coverity issues in test.
Check context before member of the context.
**Fixes:** CID 456643: Dereference null return value (NULL_RETURNS)
Use memcpy instead of strcpy to correct:
"You might overrun the 256-character fixed-size string astest.errstr by copying c->errstr without checking the length."
**Fixes:**
CID 443771: Copy into fixed size buffer (STRING_OVERFLOW)
CID 443768: Copy into fixed size buffer …

Fix Coverity warnings

---

.github/workflows/ci.yml
CMakeLists.txt

CMake 3.7.0 (released Nov. 2016) is required to get `FIND_PACKAGE(OpenSSL REQUIRED)`
to successfully generate the needed target `OpenSSL::SSL`.
This PR also adds a CI job to test that the minimum required CMake version can be used.
This showed that building with CMake 3.0 - 3.6 failed.
As reference Ubuntu 18.04 ships with CMake 3.10.

Update minimum required CMake version

---

.clang-format
CMakeLists.txt
Makefile
include/valkey/cluster.h
src/async.c
src/cluster.c
src/command.c
src/dict.c
src/dict.h
src/net.c
src/read.c
src/valkey.c
src/valkey_private.h
tests/client_test.c

- Add `SDS_INCLUDE_DIR` and `DICT_INCLUDE_DIR` to be able to replace sds and dict.
- Handle `sdsrange()` API difference
The  `sdsrange` in Valkey return void and performs no length check.
- Use same return type as Valkey from the hashFunction in dictType
Fixes issues on 32bit and macOS
- Update the nodeIterator memory blob to fit Valkeys larger dict iterator.
Changes needed in valkey repo:
https://github.com/valkey-io/valkey/compare/unstable...bjosv:valkey:refs/heads/use-libvalkey

Updates needed for replacing hiredis in the valkey repo

---

.github/workflows/ci.yml

A temporary workaround to get a successful build of libevent when vcpkg builds and installs the package.
libevent specify minimum CMake version 3.1 in its CMakeLists.txt which is incompatible with CMake >= 4.0.
Setting vcpkg to use `CMAKE_POLICY_VERSION_MINIMUM 3.5` re-enables compability with older CMake versions.
CMake: `Changed in version 4.0: Compatibility with versions of CMake older than 3.5 is removed.`

CI: workaround the Windows vcpkg build issue of `libevent` when using CMake 4.0

---

src/valkey.c
tests/CMakeLists.txt
tests/client_test.c

- Make sure the expected `char*` argument given to `%s` or `%b` is a valid pointer.
Avoids SIGSEGV in `sdscatlen`/`memcpy`.
- Output failure log when a test fails in CMake builds

Validate arguments for `%s`- and `%b`-format in `valkeyvFormatCommand`

---

.github/wordlist.txt
README.md
docs/standalone.md
include/valkey/net.h
include/valkey/valkey.h
src/net.c
src/valkey.c
tests/client_test.c

Multipath TCP (MPTCP) is an extension of the standard TCP protocol that allows a single transport connection to use multiple network interfaces or paths. MPTCP is useful for applications like bandwidth aggregation, failover, and more resilient connections.
Linux kernel starts to support MPTCP since v5.6, it's time to support it.

Introduce MPTCP

---

examples/Makefile
examples/async-ae.c
examples/async-ivykis.c
examples/async-macosx.c
examples/async-poll.c
examples/async-valkeymoduleapi.c

Some examples were missed when changing the connect callback signature in PR #142 to using a non-const context.
Add `-Werror` to the examples Makefile to find issues in CI.
Can be disabled by `USE_WERROR=0` as when building libvalkey.

Correcting the connect callback in examples

---

docs/cluster.md
include/valkey/cluster.h
src/cluster.c
tests/ct_connection.c

When a cluster client is created a few options can be configured.
The following options are now also supported and will be used when creating a connection to a single cluster node:
`VALKEY_OPT_REUSEADDR`
`VALKEY_OPT_PREFER_IPV4`
`VALKEY_OPT_PREFER_IPV6`
`VALKEY_OPT_PREFER_IP_UNSPEC`
`VALKEY_OPT_MPTCP`

Support additional client options in a cluster client

---

examples/cluster-async-tls.c
examples/cluster-async.c
examples/cluster-clientside-caching-async.c
examples/cluster-simple.c
examples/cluster-tls.c
include/valkey/cluster.h
src/sds.c
tests/test_utils.h

Update the examples, which uses the public API, but keep the macro in test only.
Additionally remove an unused define in `sds.c`.

Remove macro UNUSED from public API

---

.github/workflows/ci.yml
examples/CMakeLists.txt
examples/Makefile

- Correcting CI and the Makefile so that the installed include-files and `libvalkey_tls.a` are used by the installation tests in CI.
- Add installation test of CMake built static libraries.
- Simplify the examples CMakeLists.txt by cleanups, grouping targets using TLS and libevent, and adding comments.

Update the installation tests in CI

---

.github/workflows/ci.yml
CMakeLists.txt

Filter out `tls.h` and `rdma.h` when installing the base library and let the options `ENABLE_TLS`/`ENABLE_RDMA` determine when to install each header.
Includes a CI change to perform an install on macOS and Windows.
Additional info:
CMake documentation for `install(DIRECTORY` describes that
`PATTERN will only match a complete file or directory name occurring at the end of the full path.`

Only install headers for `TLS` and `RDMA` when enabled in CMake

---

src/cluster.c
tests/clusterclient.c
tests/clusterclient_async.c
tests/ct_connection.c
tests/ct_out_of_memory_handling.c
tests/scripts/ask-redirect-connection-error-test.sh
tests/scripts/ask-redirect-test.sh
tests/scripts/ask-redirect-using-cluster-nodes-test.sh
tests/scripts/client-disconnect-test.sh
tests/scripts/client-disconnect-without-slotmap-update-test.sh
tests/scripts/cluster-down-test.sh
tests/scripts/cluster-scale-down-test.sh
tests/scripts/command-from-callback-test.sh
tests/scripts/connect-during-cluster-startup-test.sh
tests/scripts/connect-during-cluster-startup-using-cluster-nodes-test.sh
tests/scripts/connection-error-test.sh
tests/scripts/dbsize-to-all-nodes-during-scaledown-test-async.sh
tests/scripts/dbsize-to-all-nodes-during-scaledown-test.sh
tests/scripts/dbsize-to-all-nodes-test.sh
tests/scripts/moved-redirect-test.sh
tests/scripts/moved-redirect-using-cluster-nodes-test.sh
tests/scripts/redirect-with-hostname-test.sh
tests/scripts/redirect-with-ipv6-test.sh
tests/scripts/set-get-test.sh
tests/scripts/slots-not-served-test-async.sh
tests/scripts/slots-not-served-test.sh
tests/scripts/timeout-handling-test.sh

Change so that we don't create a temporary connection when updating the slotmap in the blocking API.
When `VALKEY_FLAG_BLOCKING_INITIAL_UPDATE` is used (in the async-api) the connections are still temporary in the initial update.
Include a change in test:
- Use async initial slotmap updates by default in async tests.
Replace the command flag `--async-initial-update` in `clusterclient_async` with `--blocking-initial-update`.

Use existing connections for blocking slotmap updates

---

.github/workflows/ci.yml
src/net.c
tests/CMakeLists.txt

- Fix unused parameter in `valkeyTcpGetProtocol` when using NDEBUG.
- Fix the CMake build when disabling tests.
Setting CMAKE_BUILD_TYPE in the CMakeLists.txt for tests resulted in an mixed/weird global build type.
Instead of attempting to change the build type we can undefine any NDEBUG defined by CMake.
This to make sure asserts in tests are checked.
- Update CI due to above change.
- Run sanitizers using buld type `RelWithDebInfo` to avoid optimization issues.   
- Add valkey apt-package to cache.
- Improve CI job name when running with sanitizers.
Fixes #211

Fix `unused-parameter` warning when building with `NDEBUG`

---

.github/workflows/ci.yml

- Install OpenSSL in Windows CI using `vcpkg`.
There is a mismatch in the package index for OpenSSL in `choco` which currently fails our CI builds.
Lets use `vcpkg` that probably is a more reliable source.
- Cache the built `vcpkg` packages in CI using [vcpkg-action](https://github.com/johnwason/vcpkg-action).    
Saves about 7 minutes of runtime on the CI job `windows`.
- Remove superfluous workaround.

Fix the failing Windows CI job and add caching of vcpkg

---

.github/workflows/ci.yml
examples/CMakeLists.txt
examples/cluster-clientside-caching-async.c

Use correct include and library paths when event libraries are installed using homebrew.
Fix warnings in examples when built using `CMAKE_BUILD_TYPE=Release`.

Build examples on macOS in CI

---

include/valkey/cluster.h
src/cluster.c
tests/clusterclient.c
tests/clusterclient_async.c
tests/scripts/client-disconnect-test.sh
tests/scripts/slots-not-served-test.sh

Set the option `select_db` in `valkeyClusterOptions` to select a logical database after a successful connect.
The option is supported in both the Synchronous and Asynchronous API, and the `SELECT` command is only sent when configured to a non-zero value.
Additionally adds new flags  to the clusterclients `[--select-db NUM]` and update tests.

Add option to select a logical database
